calOne = int(input("Calcurator One : "))
calTwo = int(input("Calcurator Two : "))
print(calOne, "+", calTwo, "=", calOne + calTwo)
print(calOne, "-", calTwo, "=", calOne - calTwo)
print(calOne, "*", calTwo, "=", calOne * calTwo)
print(calOne, "/", calTwo, "=", calOne / calTwo)